# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vBbTqvJiuQzrfzoM2vMkfVdImypzxim
"""

print("Perfeito!\nAgora, selecione uma das opções a baixo:")

if escolha == 1:
  print(f"{d1} + {d2} = {d1+d2}")
if escolha == 2:
  print(f"{d1} - {d2} = {d1-d2}")

